### ISSUE TITLE
Can you upload the file "neg_sample.pickle"?

### ISSUE THREAD

**Issue by Firefly2k** [RandolphVI/Next-Basket-Recommendation#4]
Hi, dear RandolphVI,

I trying to run your code, the Anaconda with Python 3.6 (3.6.9) was already downloaded and installed, as well as, all needed frameworks also were installed... But after I run the train.py in Spyder the code ended with errors, because there is no "**_neg_sample.pickle_**" in the "_data_" folder. So, can you upload this file? Or can you give the example of its structure, from which one can understand what should be inside this file?

P.S.: I used your files "_test_sample.json_", "_train_sample.json_" and "_validation_sample.json_" as corresponding files mentioned in "_config.py_" by "_self.TESTSET_DIR_", "_self.TRAININGSET_DIR_" and "_self.VALIDATIONSET_DIR_". The only file that is absent is "**neg_sample.pickle**".

Sincerely Yours,
Sergey.

**Comment by RandolphVI** [comment]
Hi Sergey,

I have updated the README in my GitHub.
Now you can download the `neg_sample.pickle` file.

Hope it helps!

Best,
Randolph

________________________________
发件人: Firefly2k <notifications@github.com>
发送时间: 2019年12月19日 15:10
收件人: RandolphVI/Next-Basket-Recommendation <Next-Basket-Recommendation@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [RandolphVI/Next-Basket-Recommendation] Can you upload the file "neg_sample.pickle"? (#4)


Hi, dear RandolphVI,

I trying to run your code, the Anaconda with Python 3.6 (3.6.9) was already downloaded and installed, as well as, all needed frameworks also was installed... But after I run the train.py in Spyder the code ended with errors, because there is no "neg_sample.pickle" in the "data" folder. So, can you upload this file? Or can you give the example of its structure, from which one can understand what should be inside this file?

Sincerely Yours,
Sergey.

―

**Comment by RandolphVI** [comment]
@Firefly2k 

I have updated the README in my GitHub.
Now you can download the `neg_sample.pickle` file.

Hope it helps!

**Comment by Firefly2k** [comment]
@RandolphVI, thanks for your help and for the quick answer!
I will try it again with this file soon.

Best Regards!

**Comment by Firefly2k** [comment]
P.S: @RandolphVI, what is recomended RAM size to run the code with these sample files?
After first run with `neg_sample.pickle` my pc (intel i5-6500 with 8 Gb RAM)
was freezeing, because python's process used all of the RAM memory. :)

**Comment by RandolphVI** [comment]
@Firefly2k 

The RAM size of my computer is 16 GB.

**Comment by Firefly2k** [comment]
**UPD**. I removed this comment to separate Issue (off-top).

**Comment by Firefly2k** [comment]
Dear @RandolphVI, I already figured out what the structure of a pickle file is
(I lacked basic python knowledge, but now I have already solved the issue).

But any way, thanks for your code!

Best Regards.
